x-spark-common: &spark-common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  environment:
    SPARK_MODE: Worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
  networks:
    - datamasterylab

services:
  spark-master:
    <<: *spark-common
    command: /bin/sh -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "9092:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common
    command: /bin/sh -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-worker-2:
    <<: *spark-common
    command: /bin/sh -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-worker-3:
    <<: *spark-common
    command: /bin/sh -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-worker-4:
    <<: *spark-common
    command: /bin/sh -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-submit:
    <<: *spark-common
    command: /bin/sh -c "$SPARK_HOME/bin/spark-submit /opt/bitnami/spark/jobs/main.py"
    depends_on:
      - spark-master

networks:
  datamasterylab:
