services:
  spark-master:
    build: .
    hostname: spark-master
    container_name: spark-master
    ports:
      - "9092:8080"  # Spark UI
      - "7077:7077"  # Master URL
    environment:
      - SPARK_MODE=master
    volumes:
      - ./jobs:/jobs  # Mount jobs directory
      - ./jobs/input:/jobs/input  # Mount input directory
    networks:
      - spark-network

  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    depends_on:
      - spark-master
    volumes:
      - ./jobs:/jobs  # Mount jobs directory
      - ./jobs/input:/jobs/input  # Mount input directory
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
